 export { Navigation } from './Navigation/Navigation'
 export { Languages } from './Navigation/Languages'
 export { AboutMe } from './AboutMe/AboutMe'
 export { Projects } from './Projects/Projects'
 export { KpClaudiaProject } from './Projects/KpClaudia'
 export { FootballProject } from './Projects/Football'
 export { Skills } from './Skills/Skills'
 export { BasicSkills, OtherSkills, MainSkills } from './Skills/Technologies'
 export { Contact } from './Contact/Contact'
 export { ContactForm } from './Contact/Form'